Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/zesty64"
  config.vm.network "forwarded_port", guest: 80, host: 8888
  config.vm.network "forwarded_port", guest: 443, host: 4433
  config.vm.provision "shell", path: "scripts/setup.sh"
end
